// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrilhaDaMultiplicacaoAPI.Data;

#nullable disable

namespace TrilhaDaMultiplicacaoAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260816205315_AddRefreshToken")]
    partial class AddRefreshToken
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TrilhaDaMultiplicacaoAPI.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarEmoji")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BloqueadoAte")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("SecurityStamp")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TentativasLoginFalhas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NomeUsuario")
                        .IsUnique();

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("TrilhaDaMultiplicacaoAPI.Models.AlunoConquista", b =>
                {
                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<int>("ConquistaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DesbloqueadaEm")
                        .HasColumnType("datetime2");

                    b.HasKey("AlunoId", "ConquistaId");

                    b.HasIndex("ConquistaId");

                    b.ToTable("AlunoConquistas");
                });

            modelBuilder.Entity("TrilhaDaMultiplicacaoAPI.Models.Conquista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoCriterio")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ValorNecessario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Conquistas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Complete a sua primeira fase da trilha.",
                            Icone = "🥇",
                            TipoCriterio = 0,
                            Titulo = "Primeiro Passo",
                            ValorNecessario = 1
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Consiga 3 estrelas em pelo menos uma fase.",
                            Icone = "🌟",
                            TipoCriterio = 1,
                            Titulo = "Trinca de Ouro",
                            ValorNecessario = 1
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Complete 3 fases da trilha.",
                            Icone = "🔥",
                            TipoCriterio = 0,
                            Titulo = "Sequência de Craque",
                            ValorNecessario = 3
                        },
                        new
                        {
                            Id = 4,
                            Descricao = "Complete 6 fases da trilha.",
                            Icone = "🏃",
                            TipoCriterio = 0,
                            Titulo = "Meio Caminho",
                            ValorNecessario = 6
                        },
                        new
                        {
                            Id = 5,
                            Descricao = "Complete as 12 fases da trilha da multiplicação.",
                            Icone = "🏆",
                            TipoCriterio = 0,
                            Titulo = "Trilha Completa",
                            ValorNecessario = 12
                        },
                        new
                        {
                            Id = 6,
                            Descricao = "Consiga 3 estrelas em 5 fases diferentes.",
                            Icone = "✨",
                            TipoCriterio = 1,
                            Titulo = "Estrela em Dobro",
                            ValorNecessario = 5
                        },
                        new
                        {
                            Id = 7,
                            Descricao = "Acumule 300 pontos.",
                            Icone = "💰",
                            TipoCriterio = 2,
                            Titulo = "Colecionador de Pontos",
                            ValorNecessario = 300
                        },
                        new
                        {
                            Id = 8,
                            Descricao = "Acumule 800 pontos.",
                            Icone = "👑",
                            TipoCriterio = 2,
                            Titulo = "Mestre da Trilha",
                            ValorNecessario = 800
                        });
                });

            modelBuilder.Entity("TrilhaDaMultiplicacaoAPI.Models.FaseProgresso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ConcluidaEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("Estrelas")
                        .HasColumnType("int");

                    b.Property<int>("NumeroFase")
                        .HasColumnType("int");

                    b.Property<int>("Pontos")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId", "NumeroFase")
                        .IsUnique();

                    b.ToTable("FasesProgresso");
                });

            modelBuilder.Entity("TrilhaDaMultiplicacaoAPI.Models.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<string>("CodigoHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiraEm")
                        .HasColumnType("datetime2");

                    b.Property<int>("TentativasFalhas")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UsadoEm")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("TrilhaDaMultiplicacaoAPI.Models.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiraEm")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RevogadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("TrilhaDaMultiplicacaoAPI.Models.AlunoConquista", b =>
                {
                    b.HasOne("TrilhaDaMultiplicacaoAPI.Models.Aluno", "Aluno")
                        .WithMany("Conquistas")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrilhaDaMultiplicacaoAPI.Models.Conquista", "Conquista")
                        .WithMany("AlunosQueDesbloquearam")
                        .HasForeignKey("ConquistaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Conquista");
                });

            modelBuilder.Entity("TrilhaDaMultiplicacaoAPI.Models.FaseProgresso", b =>
                {
                    b.HasOne("TrilhaDaMultiplicacaoAPI.Models.Aluno", "Aluno")
                        .WithMany("Progresso")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("TrilhaDaMultiplicacaoAPI.Models.PasswordResetToken", b =>
                {
                    b.HasOne("TrilhaDaMultiplicacaoAPI.Models.Aluno", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("TrilhaDaMultiplicacaoAPI.Models.RefreshToken", b =>
                {
                    b.HasOne("TrilhaDaMultiplicacaoAPI.Models.Aluno", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("TrilhaDaMultiplicacaoAPI.Models.Aluno", b =>
                {
                    b.Navigation("Conquistas");

                    b.Navigation("Progresso");
                });

            modelBuilder.Entity("TrilhaDaMultiplicacaoAPI.Models.Conquista", b =>
                {
                    b.Navigation("AlunosQueDesbloquearam");
                });
#pragma warning restore 612, 618
        }
    }
}
