// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrilhaDaMultiplicacaoAPI.Data;

#nullable disable

namespace TrilhaDaMultiplicacaoAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("TrilhaDaMultiplicacaoAPI.Models.Aluno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarEmoji")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("TrilhaDaMultiplicacaoAPI.Models.AlunoConquista", b =>
                {
                    b.Property<int>("AlunoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConquistaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DesbloqueadaEm")
                        .HasColumnType("TEXT");

                    b.HasKey("AlunoId", "ConquistaId");

                    b.HasIndex("ConquistaId");

                    b.ToTable("AlunoConquistas");
                });

            modelBuilder.Entity("TrilhaDaMultiplicacaoAPI.Models.Conquista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FasesConcluidasNecessarias")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Conquistas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Concluiu a primeira fase da trilha.",
                            FasesConcluidasNecessarias = 1,
                            Icone = "🌱",
                            Titulo = "Primeiros passos"
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Concluiu 3 fases da trilha.",
                            FasesConcluidasNecessarias = 3,
                            Icone = "🔥",
                            Titulo = "Pegando o jeito"
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Concluiu 6 fases da trilha.",
                            FasesConcluidasNecessarias = 6,
                            Icone = "🏆",
                            Titulo = "Mestre da multiplicação"
                        });
                });

            modelBuilder.Entity("TrilhaDaMultiplicacaoAPI.Models.FaseProgresso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlunoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ConcluidaEm")
                        .HasColumnType("TEXT");

                    b.Property<int>("Estrelas")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumeroFase")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pontos")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId", "NumeroFase")
                        .IsUnique();

                    b.ToTable("FasesProgresso");
                });

            modelBuilder.Entity("TrilhaDaMultiplicacaoAPI.Models.AlunoConquista", b =>
                {
                    b.HasOne("TrilhaDaMultiplicacaoAPI.Models.Aluno", "Aluno")
                        .WithMany("Conquistas")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TrilhaDaMultiplicacaoAPI.Models.Conquista", "Conquista")
                        .WithMany("AlunosQueDesbloquearam")
                        .HasForeignKey("ConquistaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Conquista");
                });

            modelBuilder.Entity("TrilhaDaMultiplicacaoAPI.Models.FaseProgresso", b =>
                {
                    b.HasOne("TrilhaDaMultiplicacaoAPI.Models.Aluno", "Aluno")
                        .WithMany("Progresso")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("TrilhaDaMultiplicacaoAPI.Models.Aluno", b =>
                {
                    b.Navigation("Conquistas");

                    b.Navigation("Progresso");
                });

            modelBuilder.Entity("TrilhaDaMultiplicacaoAPI.Models.Conquista", b =>
                {
                    b.Navigation("AlunosQueDesbloquearam");
                });
#pragma warning restore 612, 618
        }
    }
}
